// DO NOT COMMIT real values. Run:
//   flutterfire configure --project=live-captions-xr
// to generate this file with your actual Firebase credentials.
//
// The generated file will contain platform-specific API keys, app IDs, etc.
// It is gitignored by default when generated by flutterfire.
//
// Placeholder — replace by running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run flutterfire configure to generate platform-specific options.',
        );
    }
  }

  // ⚠️  Replace these with values from: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'live-captions-xr',
    authDomain: 'live-captions-xr.firebaseapp.com',
    storageBucket: 'live-captions-xr.appspot.com',
    measurementId: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'live-captions-xr',
    storageBucket: 'live-captions-xr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'live-captions-xr',
    storageBucket: 'live-captions-xr.appspot.com',
    iosClientId: 'REPLACE_ME',
    iosBundleId: 'com.craigm26.opencastorClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'live-captions-xr',
    storageBucket: 'live-captions-xr.appspot.com',
    iosClientId: 'REPLACE_ME',
    iosBundleId: 'com.craigm26.opencastorClient',
  );
}
