import 'dart:async';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'data/services/auth_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure — real values injected by CI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Complete any pending redirect sign-in (web only).
  // Guarded by a 5s timeout — getRedirectResult() can hang if the Firebase
  // auth domain is slow or unreachable, which would block runApp() forever.
  await AuthService.handleRedirectResult()
      .timeout(const Duration(seconds: 5), onTimeout: () {});

  runApp(const ProviderScope(child: OpenCastorApp()));
}
