import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'data/services/auth_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure — real values injected by CI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Complete any pending redirect sign-in (web browsers use
  // signInWithRedirect; result is captured here on return).
  await AuthService.handleRedirectResult();

  runApp(const ProviderScope(child: OpenCastorApp()));
}
