import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Complete any pending redirect sign-in (mobile web browsers use
  // signInWithRedirect instead of signInWithPopup; result arrives here).
  await handleRedirectResult();

  runApp(const ProviderScope(child: OpenCastorApp()));
}
