#!/usr/bin/env bash
# setup_local.sh — Generate firebase_options.dart for local development
# Run this once before `flutter run`. The file is .gitignored.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

cat > "$REPO_ROOT/lib/firebase_options.dart" << 'DART'
// LOCAL DEV — generated by scripts/setup_local.sh
// Do not commit. Real values for com.craigm26.opencastorClient.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz1Vd1Eaj9QBLfmDj0rPEfJX9f3G6UPaI',
    appId: '1:360358330839:web:f35773ab2c6a78092c0b92',
    messagingSenderId: '360358330839',
    projectId: 'opencastor',
    authDomain: 'opencastor.firebaseapp.com',
    storageBucket: 'opencastor.firebasestorage.app',
    measurementId: 'G-2P14Z5H4NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1Vd1Eaj9QBLfmDj0rPEfJX9f3G6UPaI',
    appId: '1:360358330839:android:30060e51644ca3952c0b92',
    messagingSenderId: '360358330839',
    projectId: 'opencastor',
    storageBucket: 'opencastor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBORI8TZ88k6-rFiEiV04j0KpVUDmmgF-I',
    appId: '1:360358330839:ios:66f6c2a7be80c1482c0b92',
    messagingSenderId: '360358330839',
    projectId: 'opencastor',
    storageBucket: 'opencastor.firebasestorage.app',
    iosClientId: '360358330839-c615jjves4lbk0ovrgel12ausvfa92bt.apps.googleusercontent.com',
    iosBundleId: 'com.craigm26.opencastorClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBORI8TZ88k6-rFiEiV04j0KpVUDmmgF-I',
    appId: '1:360358330839:ios:66f6c2a7be80c1482c0b92',
    messagingSenderId: '360358330839',
    projectId: 'opencastor',
    storageBucket: 'opencastor.firebasestorage.app',
    iosClientId: '360358330839-c615jjves4lbk0ovrgel12ausvfa92bt.apps.googleusercontent.com',
    iosBundleId: 'com.craigm26.opencastorClient',
  );
}
DART

echo "✅  lib/firebase_options.dart written."
echo ""
echo "Now run:"
echo "  flutter devices          # find your simulator ID"
echo "  flutter run -d <id>      # e.g. -d 'iPhone 16'"
